import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MenuTop from './components/MenuTop'
import CarouselDestaque from './components/CarouselDestaque'
import PopularProducts from './components/PopularProducts'
import Footer from './components/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Lustore - Wecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuTop />
      <CarouselDestaque />
      <PopularProducts />
      <Footer />
    </>
  )
}
